name: Lambda deploy

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    name: Deploy lambda function
    runs-on: [ ubuntu-latest]
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    - name: zip Lambda Function
      run: zip -r9 lambda_function.zip lambda_function.py
    - name: AWS Deploy Lambda
      run: |
          aws lambda update-function-code --function-name MyLambdaFnc --zip-file fileb://lambda_function.zip

